# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yif-jVelT-VqHJPK_vavfET6X6KZ2tfB
"""

a = input().split()
b = []

for x in a:
    i = int(x)
    if i < 60:
        b.append(i)

print(len(b))